service: url-shortner
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:List*
        - dynamodb:DescribeReservedCapacity*
        - dynamodb:DescribeLimits
        - dynamodb:DescribeTimeToLive
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/shorten-urls*
    # - Effect: Allow
    #   Action:
    #     - cognito-idp:ListUsers
    #     - cognito-idp:AdminDeleteUser
    #     - cognito-idp:AdminDisableUser
    #     - cognito-idp:AdminEnableUser
    #     - cognito-idp:AdminGetUser
    #     - cognito-idp:AdminUpdateUserAttributes
    #     - cognito-idp:AdminSetUserPassword
    #     - cognito-idp:AdminCreateUser
    #   Resource: "*"
  environment:
    USER_POOL_CLIENT_ID: !Ref MyUserPoolClient
    USER_POOL_ID: !Ref UserPool
    BASIC_USER_ALLOWED_URLS: 100
    SHORTNER_URLS_TABLE: shorten-urls
    SHORTNER_URLS_USERS_TABLE: shorten-urls-users
    ADMIN_STATS_TABLE: shorten-urls-admin-matrix
    AWS_SES_IDENTITY: himanshumittal2014@gmail.com
frameworkVersion: 3
functions:
  healthCheck:
    handler: src/healthCheck.ping
    events:
      - http:
          path: healthCheck
          method: get
          cors: true
  addUrl:
    handler: src/url/addUrl.addUrl
    events:
      - http:
          path: urls
          method: put
          cors: true
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn
  getUrl:
    handler: src/url/getUrl.getUrl
    events:
      - http:
          path: urls
          method: get
          cors: true
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn
  deleteUrl:
    handler: src/url/deleteUrl.deleteUrl
    events:
      - http:
          path: urls
          method: delete
          cors: true
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn
  updateUrl:
    handler: src/url/updateUrl.updateUrl
    events:
      - http:
          path: urls
          method: post
          cors: true
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn
  hitUrl:
    handler: src/url-shortner/hitUrl.hitUrl
    events:
      - http:
          path: url/{uuid}
          method: get
          cors: true
  dashboard:
    handler: src/user/dashboard.dashboard
    events:
      - http:
          path: user/me
          method: get
          cors: true
          authorizer:
            name: MyCognitoAuthorizer2
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn
  signup:
    handler: src/user/signup.signup
    events:
      - http:
          path: user/signup
          method: post
          cors: true
  confirm-signup:
    handler: src/user/confirmSignup.confirmSignup
    events:
      - http:
          path: user/confirm-sign-up
          method: post
          cors: true
  signin:
    handler: src/user/signin.signin
    events:
      - http:
          path: user/sign-in
          method: post
          cors: true

resources:
  Resources:
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: url-shortner-users
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          From: ${self:provider.environment.AWS_SES_IDENTITY}
          ReplyToEmailAddress: ${self:provider.environment.AWS_SES_IDENTITY}
          SourceArn: arn:aws:ses:${self:provider.region}:${aws:accountId}:identity/${self:provider.environment.AWS_SES_IDENTITY}
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - Name: email
            AttributeDataType: String
            Required: true
            Mutable: false
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: "ROLE"
            Required: false
    MyUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      DependsOn:
        - UserPool
      Properties:
        ClientName: url-shortner-user-pool-client
        UserPoolId: !Ref UserPool
        GenerateSecret: false
        AllowedOAuthFlowsUserPoolClient: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 1
        IdTokenValidity: 1
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: days
          IdToken: days
          RefreshToken: days
    UrlShortenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SHORTNER_URLS_TABLE}
        AttributeDefinitions:
          - AttributeName: unique_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: unique_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    UrlShortenUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SHORTNER_URLS_USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: unique_id
            AttributeType: S
        KeySchema:
          - AttributeName: unique_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AdminStatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ADMIN_STATS_TABLE}
        AttributeDefinitions:
          - AttributeName: matrix_type
            AttributeType: S
        KeySchema:
          - AttributeName: matrix_type
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
#plugins:
#- serverless-offline
